POST http://localhost:3333/videos
Content-type: application/json

{
  "title": "Video Node2",
  "description": "Este é o video node",
  "duration":100
}

###
GET http://localhost:3333/videos?search=node

### 
PUT http://localhost:3333/videos/fdb2f82b-1e30-4b59-8b3b-4fa48c0df501
Content-type: application/json

{
  "title": "Video 04",
  "description": "Este é o video 05",
  "duration":100
} 